<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Generated by AI.
 *
 * @package    mod_simplequiz2
 * @copyright  2024 Dixeo (contact@dixeo.com)
 * @author     Pierre FACQ
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
$string['addquestion'] = "Aggiungi una domanda";
$string['aria_answer_text'] = 'Risposta: {$a->answer}';
$string['aria_audio'] = 'Audio: {$a->description}. Ascolta il suono.';
$string['aria_image'] = 'Immagine: {$a->description}.';
$string['aria_math'] = 'Equazione matematica.';
$string['aria_next'] = '{$a->status}: vai alla domanda successiva.';
$string['aria_no_description'] = 'nessuna descrizione';
$string['aria_question_text'] = 'Domanda {$a->order}: {$a->description}';
$string['aria_restart'] = '{$a->status}: fine dell\'attività. Puoi ricominciare o passare all\'attività successiva.';
$string['aria_video'] = 'Video: {$a->description}. Guarda il video.';
$string['attemptsdeleted'] = 'Tentativi MCQ eliminati';
$string['cantconvertcodeerror'] = 'Si è verificato un errore durante la conversione del modulo, contatta il team di supporto';
$string['check-answer'] = "Verifica la risposta";
$string['completionminattempts'] = 'Lo studente deve completare o tentare l\'attività una o più volte: ';
$string['completionminattempts:attempts'] = 'Lo studente deve completare o tentare l\'attività una o più volte: {$a}';
$string['completionminattemptsdesc'] = 'Lo studente deve completare o tentare l\'attività {$a} volte';
$string['completionminattemptsgroup'] = 'Numero minimo di tentativi';
$string['convert_success'] = "Conversione effettuata con successo";
$string['converttoquiz'] = 'Converti in attività Quiz';
$string['deletealluserdata'] = 'Elimina tutti i tentativi MCQ';
$string['deletequestion'] = "Elimina questa domanda";
$string['formanswertitle'] = 'Risposta {$a}';
$string['editquestion'] = 'Modifica domanda';
$string['correctfeedback'] = 'Feedback se la risposta è corretta';
$string['partiallycorrectfeedback'] = 'Feedback se la risposta è parzialmente corretta';
$string['incorrectfeedback'] = 'Feedback se la risposta è errata';
$string['discardquestion'] = 'Annulla modifiche';
$string['savequestion'] = 'Salva modifiche';
$string['previewanswers'] = 'Risposte';
$string['previewfeedback'] = 'Feedback';
$string['previewcorrect'] = 'Corretta';
$string['previewpartial'] = 'Parzialmente corretta';
$string['previewincorrect'] = 'Errata';
$string['formquestiontitle'] = 'Domanda {$a}';
$string['iscorrectanswer'] = 'Risposta corretta?';
$string['modulename'] = 'MCQ';
$string['modulename_help'] = 'Questa attività ti consente di condurre una serie di domande a scelta multipla.';
$string['modulenameplural'] = 'MCQ';
$string['nextquestion'] = "Domanda successiva";
$string['no-questions'] = "Attività in fase di costruzione";
$string['norightanswererror'] = 'Le domande devono avere almeno una risposta corretta.';
$string['notenoughanswerserror'] = 'Le domande devono avere almeno due risposte.';
$string['pluginadministration'] = 'Amministrazione MCQ';
$string['pluginname'] = 'MCQ';
$string['plugintitle'] = 'MCQ';
$string['privacy:metadata:core_files'] = 'L\'attività MCQ memorizza i file incorporati nell\'introduzione dell\'attività e nel contenuto delle domande.';
$string['privacy:metadata:simplequiz2_attempt_data'] = 'Dati delle risposte per sessione mentre l\'utente avanza nell\'attività.';
$string['privacy:metadata:simplequiz2_attempt_data:answers'] = 'Mappa JSON degli identificatori delle domande ai risultati delle risposte per questa sessione.';
$string['privacy:metadata:simplequiz2_attempt_data:cmid'] = 'L\'istanza del modulo del corso a cui appartiene questa sessione.';
$string['privacy:metadata:simplequiz2_attempt_data:timecreated'] = 'Quando è stato creato questo record di sessione.';
$string['privacy:metadata:simplequiz2_attempt_data:userid'] = 'L\'utente a cui appartiene questa sessione.';
$string['privacy:metadata:simplequiz2_attempts'] = 'Riepilogo di ogni tentativo dell\'utente per una data istanza di attività MCQ.';
$string['privacy:metadata:simplequiz2_attempts:cmid'] = 'L\'istanza del modulo del corso a cui appartiene questo riepilogo.';
$string['privacy:metadata:simplequiz2_attempts:cntattempt'] = 'Quanti tentativi sono stati registrati per questo utente.';
$string['privacy:metadata:simplequiz2_attempts:completed'] = 'Se l\'utente ha completato l\'attività con successo (flag specifico del plugin).';
$string['privacy:metadata:simplequiz2_attempts:timefirstattempt'] = 'Data del primo tentativo.';
$string['privacy:metadata:simplequiz2_attempts:timelastattempt'] = 'Data del tentativo più recente.';
$string['privacy:metadata:simplequiz2_attempts:userid'] = 'L\'utente a cui appartiene questo riepilogo.';
$string['question'] = 'Domanda';
$string['questionfail'] = "Risposta sbagliata";
$string['questionpartial'] = 'Risposta parzialmente corretta';
$string['questionsuccess'] = "Risposta corretta";
$string['questiontext'] = 'Testo della domanda';
$string['restart'] = "Ricomincia";
$string['result-bestscore'] = 'Miglior punteggio: {$a->score}%';
$string['result-help'] = 'Viene conservato solo il punteggio più alto.';
$string['result-score'] = 'Punteggio ottenuto: {$a->score}%';
$string['session_expired_body'] = "<p>Verrai reindirizzato alla pagina principale.<br>Effettua nuovamente l'accesso per continuare.</p>";
$string['session_expired_title'] = 'Sessione scaduta';
$string['show-results'] = 'Risultati';
$string['simplequiz2:addinstance'] = 'Aggiungi un\'attività MCQ';
$string['simplequiz2:view'] = 'Visualizza un\'attività MCQ';
$string['embed_finish'] = 'Termina';
