<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Generated by AI.
 *
 * @package    mod_simplequiz2
 * @copyright  2024 Dixeo (contact@dixeo.com)
 * @author     Pierre FACQ
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
$string['addquestion'] = "Agregar una pregunta";
$string['aria_answer_text'] = 'Respuesta: {$a->answer}';
$string['aria_audio'] = 'Audio: {$a->description}. Por favor escuche el sonido.';
$string['aria_image'] = 'Imagen: {$a->description}.';
$string['aria_math'] = 'Ecuación matemática.';
$string['aria_next'] = '{$a->status}: ir a la siguiente pregunta.';
$string['aria_no_description'] = 'sin descripción';
$string['aria_question_text'] = 'Pregunta {$a->order}: {$a->description}';
$string['aria_restart'] = '{$a->status}: fin de la actividad. Puede reiniciar o pasar a la siguiente actividad.';
$string['aria_video'] = 'Vídeo: {$a->description}. Por favor, vea el vídeo.';
$string['attemptsdeleted'] = 'Intentos de MCQ eliminados';
$string['cantconvertcodeerror'] = 'Se produjo un error al convertir el módulo, por favor contacte al equipo de soporte';
$string['check-answer'] = "Verificar la respuesta";
$string['completionminattempts'] = 'El estudiante debe completar o intentar la actividad una o más veces: ';
$string['completionminattempts:attempts'] = 'El estudiante debe completar o intentar la actividad una o más veces: {$a}';
$string['completionminattemptsdesc'] = 'El estudiante debe completar o intentar la actividad {$a} veces';
$string['completionminattemptsgroup'] = 'Número mínimo de intentos';
$string['convert_success'] = "Conversión realizada con éxito";
$string['converttoquiz'] = 'Convertir en actividad de cuestionario';
$string['deletealluserdata'] = 'Eliminar todos los intentos de MCQ';
$string['deletequestion'] = "Eliminar esta pregunta";
$string['formanswertitle'] = 'Respuesta {$a}';
$string['formquestiontitle'] = 'Pregunta {$a}';
$string['iscorrectanswer'] = '¿Respuesta correcta?';
$string['modulename'] = 'MCQ';
$string['modulename_help'] = 'Esta actividad le permite realizar una serie de preguntas de opción múltiple.';
$string['modulenameplural'] = 'MCQs';
$string['nextquestion'] = "Siguiente pregunta";
$string['no-questions'] = "Actividad en construcción";
$string['norightanswererror'] = 'Las preguntas deben tener al menos una respuesta correcta.';
$string['notenoughanswerserror'] = 'Las preguntas deben tener al menos dos respuestas.';
$string['pluginadministration'] = 'Administración de MCQ';
$string['pluginname'] = 'MCQ';
$string['plugintitle'] = 'MCQ';
$string['question'] = 'Pregunta';
$string['questionfail'] = "Respuesta incorrecta";
$string['questionpartial'] = 'Respuesta parcialmente correcta';
$string['questionsuccess'] = "Respuesta correcta";
$string['questiontext'] = 'Texto de la pregunta';
$string['restart'] = "Reiniciar";
$string['result-bestscore'] = 'Mejor puntuación: {$a->score}%';
$string['result-help'] = 'Solo se conserva la puntuación más alta.';
$string['result-score'] = 'Puntuación obtenida: {$a->score}%';
$string['session_expired_body'] = "<p>Será redirigido a la página de inicio.<br>Por favor, inicie sesión de nuevo para continuar.</p>";
$string['session_expired_title'] = 'Sesión expirada';
$string['show-results'] = 'Resultados';
$string['simplequiz2:addinstance'] = 'Agregar una actividad MCQ';
$string['simplequiz2:view'] = 'Ver una actividad MCQ';
$string['embed_finish'] = 'Finalizar';
